@extends('layouts.admin')
@section('content')
<div class="mx-auto max-w-6xl">@if(session('success'))<div class="mb-6 rounded-[10px] bg-auth-mint px-4 py-3 text-sm font-semibold">{{ session('success') }}</div>@endif @if($errors->any())<div class="mb-6 rounded-[10px] bg-auth-pink px-4 py-3 text-sm">{{ $errors->first() }}</div>@endif
<div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm text-slate-500">Espace employeur</p><h2 class="mt-1 text-3xl font-bold text-auth-ink">Bonjour, {{ $user->name }} 👋</h2><p class="mt-2 text-sm text-slate-500">Déposez des dossiers complets et suivez leur traitement par l’IAI.</p></div><a href="#new-request" class="rounded-[5px] bg-auth-ink px-5 py-3 text-sm font-semibold text-white">+ Nouvelle demande</a></div>
<div class="mt-8 grid gap-5 md:grid-cols-3"><div class="rounded-[5px] bg-white p-6 shadow-sm"><p class="text-sm text-slate-500">Demandes envoyées</p><p class="mt-3 text-3xl font-bold">{{ $requests->count() }}</p></div><div class="rounded-[5px] bg-auth-yellow p-6"><p class="text-sm text-slate-600">En attente</p><p class="mt-3 text-3xl font-bold">{{ $requests->where('status', 'pending')->count() }}</p></div><div class="rounded-[5px] bg-auth-mint p-6"><p class="text-sm text-slate-600">Validées</p><p class="mt-3 text-3xl font-bold">{{ $requests->where('status', 'validated')->count() }}</p></div></div>
<section id="new-request" class="mt-8 rounded-[5px] bg-white p-6 shadow-sm"><h3 class="font-bold text-auth-ink">Nouvelle demande de vérification</h3><p class="mt-1 text-sm text-slate-500">Les champs d’identité et de consentement rendent le contrôle traçable et évitent une vérification abusive.</p><form method="POST" action="{{ route('employer.requests.store') }}" enctype="multipart/form-data" class="mt-6 space-y-6">@csrf
<div><h4 class="text-sm font-bold text-auth-ink">Candidat</h4><div class="mt-3 grid gap-3 sm:grid-cols-2"><input name="holder_name" required placeholder="Nom complet du titulaire" class="rounded-[5px] border-slate-200 bg-slate-50 px-3 py-3 text-sm"><input name="candidate_id_number" placeholder="CNI / passeport (optionnel)" class="rounded-[5px] border-slate-200 bg-slate-50 px-3 py-3 text-sm"><input name="candidate_birth_date" type="date" class="rounded-[5px] border-slate-200 bg-slate-50 px-3 py-3 text-sm"><input name="candidate_birth_place" placeholder="Lieu de naissance" class="rounded-[5px] border-slate-200 bg-slate-50 px-3 py-3 text-sm"><input name="candidate_email" type="email" placeholder="E-mail du candidat" class="rounded-[5px] border-slate-200 bg-slate-50 px-3 py-3 text-sm"><input name="candidate_phone" placeholder="Téléphone du candidat" class="rounded-[5px] border-slate-200 bg-slate-50 px-3 py-3 text-sm"></div></div>
<div><h4 class="text-sm font-bold text-auth-ink">Diplôme à contrôler</h4><div class="mt-3 grid gap-3 sm:grid-cols-2"><input name="diploma_number" required placeholder="Numéro officiel du diplôme" class="rounded-[5px] border-slate-200 bg-slate-50 px-3 py-3 text-sm"><select name="program" required class="rounded-[5px] border-slate-200 bg-slate-50 px-3 py-3 text-sm"><option value="">Type de diplôme</option><option>DTS</option><option>Licence professionnelle</option><option>Ingénieur des travaux informatiques</option><option>Ingénieur de conception</option></select><input name="graduation_year" required type="number" min="1950" max="2100" placeholder="Année d’obtention" class="rounded-[5px] border-slate-200 bg-slate-50 px-3 py-3 text-sm"><input name="employment_position" required placeholder="Poste visé" class="rounded-[5px] border-slate-200 bg-slate-50 px-3 py-3 text-sm"><input name="employment_reference" placeholder="Référence de l’offre / recrutement" class="rounded-[5px] border-slate-200 bg-slate-50 px-3 py-3 text-sm sm:col-span-2"><textarea name="verification_purpose" required placeholder="Objet précis de la vérification et contexte du recrutement" class="min-h-24 rounded-[5px] border-slate-200 bg-slate-50 px-3 py-3 text-sm sm:col-span-2"></textarea></div></div>
<div><h4 class="text-sm font-bold text-auth-ink">Pièces justificatives</h4><div class="mt-3 grid gap-3 sm:grid-cols-2"><label class="text-xs font-semibold text-slate-500">Pièce d’identité<input name="candidate_document" type="file" accept=".pdf,.jpg,.jpeg,.png" class="mt-2 block w-full rounded-[5px] border border-dashed border-slate-300 p-3 text-xs"></label><label class="text-xs font-semibold text-slate-500">Copie du diplôme<input name="diploma_document" type="file" accept=".pdf,.jpg,.jpeg,.png" class="mt-2 block w-full rounded-[5px] border border-dashed border-slate-300 p-3 text-xs"></label><label class="text-xs font-semibold text-slate-500">Relevé de notes<input name="transcript_document" type="file" accept=".pdf,.jpg,.jpeg,.png" class="mt-2 block w-full rounded-[5px] border border-dashed border-slate-300 p-3 text-xs"></label><label class="text-xs font-semibold text-slate-500">Autorisation signée du candidat<input name="authorization_document" type="file" accept=".pdf,.jpg,.jpeg,.png" class="mt-2 block w-full rounded-[5px] border border-dashed border-slate-300 p-3 text-xs"></label></div></div>
<label class="flex items-start gap-3 text-sm"><input name="candidate_consent" type="checkbox" value="1" required class="mt-1"><span>Je confirme disposer de l’autorisation du candidat pour cette vérification et utiliser ses données uniquement pour le recrutement indiqué.</span></label><button class="w-full rounded-[5px] bg-auth-ink px-4 py-3 font-semibold text-white">Soumettre le dossier complet</button></form></section>
<section class="mt-8 rounded-[5px] bg-white p-6 shadow-sm"><h3 class="font-bold">Mes demandes récentes</h3><div class="mt-5 divide-y divide-slate-100">@forelse($requests as $request)<div class="flex flex-wrap items-center justify-between gap-3 py-4"><div><p class="font-semibold">{{ $request->reference }}</p><p class="text-sm text-slate-500">{{ $request->holder_name }} · {{ $request->program }} · {{ $request->diploma_number }}</p></div><span class="rounded-[5px] px-3 py-1 text-xs font-semibold {{ $request->status === 'validated' ? 'bg-auth-mint' : ($request->status === 'rejected' ? 'bg-auth-pink' : 'bg-auth-yellow') }}">{{ $request->status === 'validated' ? 'Validée' : ($request->status === 'rejected' ? 'Rejetée' : 'En attente') }}</span></div>@empty<p class="py-10 text-center text-sm text-slate-400">Aucune demande pour le moment.</p>@endforelse</div></section></div>
@endsection
