@extends('layouts.admin')
@section('content')
@php($item = $verificationRequest)
@php($official = $officialDiploma)
@php($normalize = fn ($value) => preg_replace('/\s+/', ' ', trim(mb_strtolower(\Illuminate\Support\Str::ascii((string) $value)))) )
@php($same = function ($a, $b) use ($normalize) {
    $left = $normalize($a);
    $right = $normalize($b);
    $aliases = ['genie logiciel' => 'genie logiciel', 'systeme et reseau' => 'systeme et reseau', 'systemes et reseaux' => 'systeme et reseau', 'software engineering' => 'software engineering'];
    return ($aliases[$left] ?? $left) === ($aliases[$right] ?? $right);
})
<div class="mx-auto max-w-6xl"><a href="{{ route('admin.dashboard') }}#requests" class="text-sm font-semibold text-auth-ink">← Retour aux demandes</a>
@if(session('success'))<div class="mt-5 rounded-[10px] bg-auth-mint px-4 py-3 text-sm font-semibold">{{ session('success') }}</div>@endif @if($errors->any())<div class="mt-5 rounded-[10px] bg-auth-pink px-4 py-3 text-sm">{{ $errors->first() }}</div>@endif
<div class="mt-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm text-slate-500">Dossier de vérification</p><h2 class="mt-1 text-3xl font-bold text-auth-ink">{{ $item->reference }}</h2><p class="mt-2 text-sm text-slate-500">Créé le {{ $item->created_at?->format('d/m/Y à H:i') }}</p></div><span class="rounded-[10px] px-4 py-2 text-sm font-bold {{ $item->status === 'validated' ? 'bg-auth-mint' : ($item->status === 'rejected' ? 'bg-auth-pink' : 'bg-auth-yellow') }}">{{ $item->status === 'validated' ? 'Validée' : ($item->status === 'rejected' ? 'Rejetée' : 'En attente') }}</span></div>
<section class="mt-8 rounded-[10px] bg-white p-6 shadow-sm"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h3 class="font-bold text-auth-ink">Correspondance dans la base IAI</h3><p class="mt-1 text-sm text-slate-500">La recherche officielle est effectuée uniquement avec le numéro du diplôme.</p></div><span class="rounded-[10px] px-3 py-2 text-xs font-bold {{ $official ? 'bg-auth-mint text-emerald-800' : 'bg-auth-pink text-rose-800' }}">{{ $official ? 'Correspondance trouvée' : 'Aucune correspondance' }}</span></div>@if($official)<div class="mt-5 overflow-x-auto"><table class="w-full min-w-[680px] text-left text-sm"><thead class="border-b border-slate-100 text-xs uppercase tracking-wider text-slate-400"><tr><th class="pb-3">Champ</th><th class="pb-3">Demande employeur</th><th class="pb-3">Base IAI</th><th class="pb-3">Comparaison</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach([['Titulaire', $item->holder_name, $official->holder_name, $same($item->holder_name, $official->holder_name)], ['Type', $item->diploma_type ?: $item->program, $official->diploma_type ?: $official->program, $same($item->diploma_type ?: $item->program, $official->diploma_type ?: $official->program)], ['Filière', $item->specialty ?: $item->program, $official->specialty ?: $official->program, $same($item->specialty ?: $item->program, $official->specialty ?: $official->program)], ['Année', $item->graduation_year, $official->graduation_year, (string) $item->graduation_year === (string) $official->graduation_year], ['Moyenne', $item->declared_average ?: 'Non déclarée', $official->average ?: 'Non renseignée', !$item->declared_average || (string) $item->declared_average === (string) $official->average]] as [$label, $submitted, $stored, $matches])<tr><td class="py-3 font-semibold text-auth-ink">{{ $label }}</td><td class="py-3 text-slate-600">{{ $submitted }}</td><td class="py-3 text-slate-600">{{ $stored }}</td><td class="py-3"><span class="rounded-full px-2 py-1 text-xs font-semibold {{ $matches ? 'bg-auth-mint text-emerald-800' : 'bg-auth-pink text-rose-800' }}">{{ $matches ? 'Correspondant' : 'À examiner' }}</span></td></tr>@endforeach</tbody></table></div><div class="mt-4 rounded-[10px] bg-auth-blue/30 p-4 text-sm text-auth-ink"><strong>Numéro :</strong> {{ $item->diploma_number }} — ce numéro est celui qui a permis de retrouver la fiche officielle.</div>@endif</section>
<div class="mt-6 grid gap-6 lg:grid-cols-2"><section class="rounded-[10px] bg-white p-6 shadow-sm"><h3 class="font-bold text-auth-ink">Identité du candidat</h3><dl class="mt-5 grid gap-4 sm:grid-cols-2">@foreach([['Nom complet', $item->holder_name], ['Date de naissance', $item->candidate_birth_date?->format('d/m/Y') ?: 'Non renseignée'], ['Lieu de naissance', $item->candidate_birth_place ?: 'Non renseigné'], ['Pièce d’identité', $item->candidate_id_number ?: 'Non renseignée'], ['E-mail', $item->candidate_email ?: 'Non renseigné'], ['Téléphone', $item->candidate_phone ?: 'Non renseigné']] as [$label, $value])<div><dt class="text-xs text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm font-semibold text-auth-ink">{{ $value }}</dd></div>@endforeach</dl></section><section class="rounded-[10px] bg-white p-6 shadow-sm"><h3 class="font-bold text-auth-ink">Contexte de la demande</h3><dl class="mt-5 grid gap-4 sm:grid-cols-2">@foreach([['Entreprise', $item->employer?->company_legal_name ?: $item->employer?->name], ['Demandeur', $item->requester_name ?: $item->employer?->name], ['Poste visé', $item->employment_position ?: 'Non renseigné'], ['Référence recrutement', $item->employment_reference ?: 'Non renseignée'], ['Consentement candidat', $item->candidate_consent ? 'Confirmé' : 'Non confirmé']] as [$label, $value])<div><dt class="text-xs text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm font-semibold text-auth-ink">{{ $value }}</dd></div>@endforeach</dl><p class="mt-5 text-sm leading-6 text-slate-600">{{ $item->verification_purpose ?: 'Motif non renseigné' }}</p></section></div>
<section class="mt-6 rounded-[10px] bg-white p-6 shadow-sm"><h3 class="font-bold text-auth-ink">Pièces justificatives</h3><div class="mt-5 grid gap-3 sm:grid-cols-2">@foreach([['candidate', 'Pièce d’identité', $item->candidate_document_path], ['diploma', 'Copie du diplôme', $item->diploma_document_path], ['transcript', 'Relevé de notes', $item->transcript_document_path], ['authorization', 'Autorisation signée', $item->authorization_document_path]] as [$key, $label, $path])<div class="flex items-center justify-between rounded-[10px] bg-slate-50 px-4 py-3"><span class="text-sm font-semibold text-auth-ink">{{ $label }}</span>@if($path)<a href="{{ route('admin.requests.document', [$item, $key]) }}" class="rounded-[5px] bg-auth-blue px-3 py-2 text-xs font-bold text-auth-ink">Télécharger</a>@else<span class="text-xs text-slate-400">Non déposée</span>@endif</div>@endforeach</div></section>
@if($official)<section class="mt-6 rounded-[10px] border border-auth-blue/50 bg-white p-6 shadow-sm"><h3 class="font-bold text-auth-ink">Corriger la fiche officielle</h3><p class="mt-1 text-sm text-slate-500">Utilisez cette section si le diplôme existe mais qu’une note, une filière ou une information est incorrecte dans la base.</p><form method="POST" action="{{ route('admin.diplomas.update', $official) }}" class="mt-5 grid gap-3 sm:grid-cols-2">@csrf @method('PATCH')<input name="holder_name" required value="{{ $official->holder_name }}" placeholder="Titulaire" class="form-control"><input value="{{ $official->number }}" disabled class="form-control bg-slate-100"><select name="diploma_type" required class="form-control"><option @selected($official->diploma_type === 'DTS')>DTS</option><option @selected($official->diploma_type === 'Licence professionnelle')>Licence professionnelle</option><option @selected($official->diploma_type === 'Ingénieur des travaux informatiques')>Ingénieur des travaux informatiques</option><option @selected($official->diploma_type === 'Ingénieur de conception')>Ingénieur de conception</option></select><select name="program" required class="form-control"><option @selected($official->program === 'Génie logiciel')>Génie logiciel</option><option @selected($official->program === 'Système et réseau')>Système et réseau</option><option @selected($official->program === 'Software Engineering')>Software Engineering</option></select><input name="graduation_year" required type="number" value="{{ $official->graduation_year }}" class="form-control"><input name="average" type="number" step="0.01" min="0" max="20" value="{{ $official->average }}" placeholder="Moyenne / 20" class="form-control"><input name="mention" value="{{ $official->mention }}" placeholder="Mention" class="form-control"><textarea name="correction_note" required placeholder="Motif de la correction : note incorrecte, filière, identité…" class="form-control min-h-24 sm:col-span-2"></textarea><button class="rounded-[5px] bg-auth-blue px-4 py-3 text-sm font-bold text-auth-ink sm:col-span-2">Enregistrer la correction</button></form>@if($official->corrected_at)<p class="mt-4 text-xs text-slate-500">Dernière correction le {{ $official->corrected_at->format('d/m/Y à H:i') }}. {{ $official->correction_note }}</p>@endif</section>@endif
@if($otherDiplomas->isNotEmpty())<section class="mt-6 rounded-[10px] bg-white p-6 shadow-sm"><h3 class="font-bold text-auth-ink">Autres diplômes du même étudiant</h3><p class="mt-1 text-sm text-slate-500">Un étudiant peut posséder plusieurs diplômes. Chaque numéro reste une fiche indépendante.</p><div class="mt-4 grid gap-3 sm:grid-cols-2">@foreach($otherDiplomas as $other)<div class="rounded-[10px] border border-slate-100 p-4"><p class="font-semibold text-auth-ink">{{ $other->diploma_type ?: $other->program }}</p><p class="text-sm text-slate-500">{{ $other->number }} · {{ $other->graduation_year }}</p></div>@endforeach</div></section>@endif
@if($item->status === 'pending')<section class="mt-6 rounded-[10px] border border-auth-blue/50 bg-white p-6 shadow-sm"><h3 class="font-bold text-auth-ink">Décision administrative</h3><p class="mt-1 text-sm text-slate-500">La validation est possible uniquement si une correspondance par numéro est trouvée.</p><div class="mt-5 flex flex-wrap gap-3"><form method="POST" action="{{ route('admin.requests.decide', $item) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="validated"><input type="hidden" name="decision_note" value="Correspondance du numéro confirmée dans la base IAI."><button class="rounded-[5px] bg-auth-blue px-5 py-3 text-sm font-bold text-auth-ink">Valider après contrôle</button></form><form method="POST" action="{{ route('admin.requests.decide', $item) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="rejected"><input type="hidden" name="decision_note" value="Dossier rejeté après examen administratif."><button class="rounded-[5px] bg-auth-pink px-5 py-3 text-sm font-bold text-auth-ink">Rejeter la demande</button></form></div></section>@endif
</div><style>.form-control{width:100%;border-radius:5px;border:1px solid #e2e8f0;background:#f8fafc;padding:.75rem;font-size:.875rem}</style>
@endsection
