@extends('layouts.admin')
@section('content')
@php($item = $verificationRequest)
<div class="mx-auto max-w-6xl">
    <a href="{{ route('admin.dashboard') }}#requests" class="text-sm font-semibold text-auth-ink">← Retour aux demandes</a>
    @if(session('success'))<div class="mt-5 rounded-[10px] bg-auth-mint px-4 py-3 text-sm font-semibold">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="mt-5 rounded-[10px] bg-auth-pink px-4 py-3 text-sm">{{ $errors->first() }}</div>@endif
    <div class="mt-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm text-slate-500">Dossier de vérification</p><h2 class="mt-1 text-3xl font-bold text-auth-ink">{{ $item->reference }}</h2><p class="mt-2 text-sm text-slate-500">Créé le {{ $item->created_at?->format('d/m/Y à H:i') }}</p></div><span class="rounded-[10px] px-4 py-2 text-sm font-bold {{ $item->status === 'validated' ? 'bg-auth-mint' : ($item->status === 'rejected' ? 'bg-auth-pink' : 'bg-auth-yellow') }}">{{ $item->status === 'validated' ? 'Validée' : ($item->status === 'rejected' ? 'Rejetée' : 'En attente') }}</span></div>
    <div class="mt-8 grid gap-6 lg:grid-cols-2">
        <section class="rounded-[10px] bg-white p-6 shadow-sm"><h3 class="font-bold text-auth-ink">Identité du candidat</h3><dl class="mt-5 grid gap-4 sm:grid-cols-2">@foreach([['Nom complet', $item->holder_name], ['Date de naissance', $item->candidate_birth_date?->format('d/m/Y') ?: 'Non renseignée'], ['Lieu de naissance', $item->candidate_birth_place ?: 'Non renseigné'], ['Pièce d’identité', $item->candidate_id_number ?: 'Non renseignée'], ['E-mail', $item->candidate_email ?: 'Non renseigné'], ['Téléphone', $item->candidate_phone ?: 'Non renseigné']] as [$label, $value])<div><dt class="text-xs text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm font-semibold text-auth-ink">{{ $value }}</dd></div>@endforeach</dl></section>
        <section class="rounded-[10px] bg-white p-6 shadow-sm"><h3 class="font-bold text-auth-ink">Diplôme déclaré</h3><dl class="mt-5 grid gap-4 sm:grid-cols-2">@foreach([['Type', $item->diploma_type ?: $item->program], ['Filière', $item->specialty ?: $item->program], ['Numéro', $item->diploma_number], ['Année', $item->graduation_year], ['Moyenne déclarée', $item->declared_average ? $item->declared_average.'/20' : 'Non renseignée'], ['Correspondance base IAI', $item->diploma ? 'Trouvée' : 'Introuvable']] as [$label, $value])<div><dt class="text-xs text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm font-semibold {{ $label === 'Correspondance base IAI' ? ($item->diploma ? 'text-emerald-700' : 'text-rose-700') : 'text-auth-ink' }}">{{ $value }}</dd></div>@endforeach</dl>@if($item->diploma)<div class="mt-5 rounded-[10px] bg-auth-blue/30 p-4 text-sm"><p class="font-bold text-auth-ink">Enregistrement officiel correspondant</p><p class="mt-1 text-slate-600">{{ $item->diploma->holder_name }} · {{ $item->diploma->number }} · {{ $item->diploma->graduation_year }}</p><p class="mt-1 text-slate-600">Moyenne : {{ $item->diploma->average ?: 'Non renseignée' }} · Mention : {{ $item->diploma->mention ?: 'Non renseignée' }}</p></div>@endif</section>
        <section class="rounded-[10px] bg-white p-6 shadow-sm"><h3 class="font-bold text-auth-ink">Contexte de la demande</h3><dl class="mt-5 grid gap-4 sm:grid-cols-2">@foreach([['Entreprise', $item->employer?->company_legal_name ?: $item->employer?->name], ['Demandeur', $item->requester_name ?: $item->employer?->name], ['Poste visé', $item->employment_position ?: 'Non renseigné'], ['Référence recrutement', $item->employment_reference ?: 'Non renseignée'], ['Consentement candidat', $item->candidate_consent ? 'Confirmé' : 'Non confirmé']] as [$label, $value])<div><dt class="text-xs text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm font-semibold text-auth-ink">{{ $value }}</dd></div>@endforeach</dl><div class="mt-5"><p class="text-xs text-slate-400">Motif</p><p class="mt-1 text-sm leading-6 text-slate-600">{{ $item->verification_purpose ?: 'Non renseigné' }}</p></div></section>
        <section class="rounded-[10px] bg-white p-6 shadow-sm"><h3 class="font-bold text-auth-ink">Pièces justificatives</h3><div class="mt-5 space-y-3">@foreach([['candidate', 'Pièce d’identité', $item->candidate_document_path], ['diploma', 'Copie du diplôme', $item->diploma_document_path], ['transcript', 'Relevé de notes', $item->transcript_document_path], ['authorization', 'Autorisation signée', $item->authorization_document_path]] as [$key, $label, $path])<div class="flex items-center justify-between rounded-[10px] bg-slate-50 px-4 py-3"><span class="text-sm font-semibold text-auth-ink">{{ $label }}</span>@if($path)<a href="{{ route('admin.requests.document', [$item, $key]) }}" class="rounded-[5px] bg-auth-blue px-3 py-2 text-xs font-bold text-auth-ink">Télécharger</a>@else<span class="text-xs text-slate-400">Non déposée</span>@endif</div>@endforeach</div></section>
    </div>
    @if($item->status === 'pending')<section class="mt-6 rounded-[10px] border border-auth-blue/50 bg-white p-6 shadow-sm"><h3 class="font-bold text-auth-ink">Décision administrative</h3><p class="mt-1 text-sm text-slate-500">La validation est possible uniquement si le numéro correspond à un diplôme de la base IAI.</p><div class="mt-5 flex flex-wrap gap-3"><form method="POST" action="{{ route('admin.requests.decide', $item) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="validated"><input type="hidden" name="decision_note" value="Correspondance du numéro confirmée dans la base IAI."><button class="rounded-[5px] bg-auth-blue px-5 py-3 text-sm font-bold text-auth-ink">Valider après contrôle</button></form><form method="POST" action="{{ route('admin.requests.decide', $item) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="rejected"><input type="hidden" name="decision_note" value="Dossier rejeté après examen administratif."><button class="rounded-[5px] bg-auth-pink px-5 py-3 text-sm font-bold text-auth-ink">Rejeter la demande</button></form></div></section>@endif
    @if($item->processed_at)<section class="mt-6 rounded-[10px] bg-white p-6 shadow-sm"><h3 class="font-bold text-auth-ink">Historique de décision</h3><p class="mt-2 text-sm text-slate-600">Traitée le {{ $item->processed_at->format('d/m/Y à H:i') }} par {{ $item->processor?->name ?: 'Administrateur IAI' }}.</p><p class="mt-2 text-sm text-slate-600">{{ $item->decision_note ?: 'Aucune note.' }}</p></section>@endif
</div>
@endsection
